---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователь должен иметь возможность войти в личный кабинет.
  - Пользователь должен иметь возможность выйти из личного кабинета.
  - Пользователь должен иметь возможность принять участие в игре без регистрации.
  - Пользователь должен иметь возможность востановить пароль.
  - Авторизированный пользователь должен иметь возможность просматривать информацию о турнирах.
  - Пользователь должен иметь возможность учавствовать в турнире.
  - Пользователь должен иметь возможность создать турнир.
  - Пользователь должен иметь возможность просматривать рейтинг пользователей.
  - Пользователь должен иметь возможность искать конкретного пользователя в списке.
  - Пользователь должен иметь возможность просматривать задачи.
  - Пользователь должен иметь возможность создать новую задачу.
  - Пользователь должен иметь возможность изменить свои данные в личном кабинете.
  - Пользователь должен иметь возможность просматривать исходный код игры на Githab.
  - Пользователь должен иметь возможность из личного кабинета перейти на сайт Hexlet.
  - Пользователь должен иметь возможность перейти в сообщество игры в телеграмм канале.
  - Авторизированный пользователь должен иметь возможность просматривать завершенные игры.
  - Авторизированный пользователь должен иметь возможность просматривать статистику игроков.
  - Авторизированный пользователь должен иметь возможность в личном кабинете вести переписку в чате.
  - Пользователь должен иметь возможность во время переписки использовать смайлы.
  - Авторизированный пользователь должен иметь возможность в личном кабинете пригласить другого пользователя в игру.
  - Авторизированный пользователь должен иметь возможность в личном кабинете отправить личное сообщение другому пользователю.
  - Авторизованный пользователь имеет возможность создать игру.
  - Авторизованый пользователь имеет возможность принять участие в созданной игре.
  - Пользователь должен иметь возможность выбрать во время игры язык програмирования. 
  - Пользователь должен иметь возможность во время игры просматривать задачу на английском и русском языках.
  - Пользователь долежн иметь возможность во время игры проверить решение.
  - Пользователь должен иметь возможность во время игры просматривать поле игры соперника.
  - Пользователь должен иметь возможность просмотреть повтор игры.
  - Пользователь должен иметь возможность во время игры сбросить редактор.
  - Пользователь должен иметь возможность предложить реванш сопернику.
  - Пользователь должен иметь возможность покинуть игру.
  - Пользователь должен иметь возможность из игры вернуться в личный кабинет.
  non-functional:
  - Сайт должен быть совместим с последними версиями браузеров.
  - Сайт должен быть адаптирован для мобильных устройств.
  
  implicit:
  - - Сайт должен быть безопасным и защищать данные пользователя.
  - - Пользователь должен иметь возможность просматривать профили создателей игры на Githab.
