---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователь должен иметь возможность войти в личный кабинет.
  - Пользователь должен иметь возможность выйти из личного кабинета.
  - Пользователь должен иметь возможность принять участие в игре без регистрации.
  - Пользователь должен иметь возможность восстановить пароль.
  - Авторизированный пользователь должен иметь возможность просматривать информацию о турнирах.
  - Пользователь должен иметь возможность создать турнир.
  - Пользователь должен иметь возможность просматривать рейтинг пользователей.
  - Пользователь должен иметь возможность искать конкретного пользователя в списке.
  - Пользователь должен иметь возможность просматривать задачи.
  - Пользователь должен иметь возможность создать новую задачу.
  - Пользователь должен иметь возможность изменить свои данные в личном кабинете.
  - Пользователь должен иметь возможность просматривать исходный код игры на Githab.
  - Пользователь должен иметь возможность из личного кабинета перейти на сайт Hexlet.
  - Пользователь должен иметь возможность перейти в сообщество игры в телеграмм канале.
  - Авторизированный пользователь должен иметь возможность просматривать завершенные игры.
  - Авторизированный пользователь должен иметь возможность в личном кабинете вести переписку в чате.
  - Пользователь должен иметь возможность во время переписки использовать смайлы.
  - Авторизированный пользователь должен иметь возможность пригласить другого пользователя в игру.
  - Авторизированный пользователь должен иметь возможность отправить личное сообщение другому пользователю.
  - Авторизованный пользователь имеет возможность создать игру.
  - Авторизованный пользователь имеет возможность принять участие в созданной игре.
  - Пользователь должен иметь возможность выбрать во время игры язык программирования. 
  - Пользователь должен иметь возможность во время игры просматривать задачу на английском и русском языках.
  - Пользователь должен иметь возможность во время игры проверить решение.
  - Пользователь должен иметь возможность во время игры просматривать свой редактор и редактор соперника.
  - Пользователь должен иметь возможность просмотреть повтор игры.
  - Пользователь должен иметь возможность во время игры сбросить редактор.
  - Пользователь должен иметь возможность предложить реванш сопернику.
  - Пользователь должен иметь возможность сдаться во время игры.
  - Пользователь должен иметь возможность из игры вернуться в личный кабинет.
  - В форме регистрации поле "Nickname" может содержать буквы, цифры и символы подчеркивания, должен начинаться с латинской буквы и должен быть от 3 до 16 символов
  - В форме регистрации поле "Password Confirmation" должен быть от 6 до 16 символов и совпадать с полем " Password"
non-functional:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть удобным на мобильном устройстве.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть способен обрабатывать большое количество трафика, минимум 1000 максимум 5000 пользователей.
implicit:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Пользователь должен иметь возможность просматривать профили создателей игры на Githab.
  - Во время регистрации и входа в систему при вводе не корректных данных система должна выдавать сообщение об ошибке. 
